### ISSUE TITLE
Zaczynamy

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/Malyna#2]
Okej. 
To chciałbym przedstawić ogólną wizję bota, która będzie dosyć Ciekawa.
Język: **Python 3**  ( wg. @adrian17 lepsze wsparcie dla unicodu itd ) 
Co do samej części obsługującej protokół IRC.. warto zerknąć do bota Adriana jak on wykorzystał niektóre biblioteki oraz jak [fajnie rozbił na moduły](https://github.com/adrian17/inzbot/blob/master/inzbot.py#L6).

Dlatego aplikacja zostanie podzielona na odpowiednie moduły. 
Moduł do linków.
Moduł do jakiś komunikatów, patrz  #1 .

Teraz część funkcjonalna:
### Prompt:
- [x]  <s>Dodać możliwość zmiany ustawień promptu, domyślny: **>** </s>
- [x]  Prywatne wiadomości do bota powinny być traktowane jak komendy
  ### Komendy:
  <s>
- [x] **botinfo** komenda zwracająca aktualne informacje na temat bota np. w jakich celach został stworzony. 
- [x] **gogluj** komenda która po otrzymaniu jakiegoś ciągu tekstu w argumencie zwróci skrócony link do http://lmgtfy.com/?q=  gdzie parametr q to treść zakodowana zapytania.  Taka komenda pozwoli wskazywać nowym użytkownikom jak szukać w google :smile: Wpisanie samo googluj zwraca informacje o przeznaczeniu tej komendy.
- [x] **linki**  po wpisaniu tej komendy bot powinien zwrócić informacje na temat aktualnie przechowywanych linków do tematów najczęściej powtarzających się na forum. Aby nie robić spamu fajnie, jakby bot taką informację wysyłał na PW. Zaś na chacie informował w postaci: /me wysyłam zbiór linków do %nick% zakładamy, że linków będzie sporo.
  - \- [x] **linki[TEXT]** Jako iż linki przechowują tablicę gdzie klucz to nazwa powtarzającego się tematu, to odwołanie się w sposób `>linki[Fontello]` zwrócić powinno użytkownikowi w prywatnej wiadomości link do tematu z problemem fontello. Przykład?  `>linki[spoj]` → `Temat którego szukasz jest tutaj: http://tinyurl.com/jeb476o` Czy informacje tą wyświetlamy na kanale, czy priv? Moim zdaniem na kanale ;)
    </s>
    Na razie tyle.

**Comment by event15** [comment]
Polecam aby stworzyć komendę admina, która będzie umożliwiała zmianę prompta bez "reconectu" bota.

**Comment by adrian17** [comment]
U mnie zmiana prompta jest dość prosta: https://github.com/adrian17/inzbot/blob/master/plugins/admin.py#L80

(i mi smutno że nie mogliście w zamian rozwijać mojego :P )

**Comment by efiku** [comment]
Jeżeli pozwolisz na forka.. to czemu nie. Podstawka by już była.. :)
Edit: 
Padł pomysł, aby napisać od podstaw i każdy się coś nauczy. 
Byłoby miło gdyby @adrian17 brał w tym też udział:)

**Comment by Kamil15** [comment]
Python 3?
Obecnie co widzę to Python 2.7, można to spojrzeć jak np. po string.split albo po print.
w Pythonie 3 zamiast string.split powinno być str.split a print jest funkcją i trzeba go wykonywać jak każdą inną funkcję.

Warto dodać biblioteki, po kiedy chciałem edytować kod to mi nie pozwalały pewne czynności - nie wie czym jest lmgtfy, nie wie czym jest lxml,html.
Co uniemożliwia ulepszanie kodu przez innych osób.
Więc zróbcie jakiś katalog na pluginy albo cały "projekt" wrzucić na github.
Albo jakieś linki do lib przynajmniej.
znacząco ułatwi wspólną pracę.
Pozdrawiam.

**Comment by adrian17** [comment]
```
w Pythonie 3 zamiast string.split powinno być str.split 
```

Nieprawda, zawsze było str.split. A konkretniej, idiomatyczna jest metoda: "asdf asdf".split()

> Co uniemożliwia ulepszanie kodu przez innych osób.
> Więc zróbcie jakiś katalog na pluginy albo cały "projekt" wrzucić na github.

Sam sobie powinieneś instalować biblioteki, tylko powinna być lista zależności projektu w requirements.txt.

**Comment by Kamil15** [comment]
> Nieprawda, zawsze było str.split. A konkretniej, idiomatyczna jest metoda: "asdf asdf".split()

Dlaczego nie prawda? jak string.split nie działa na Python 3?
Ja nic nie mówię że str w Python 2.7 nie ma tylko że w Python 3 nie ma czegoś takiego jak string.split
I co ma związek "asdadsad".split() z dyskusją?

> Sam sobie powinieneś instalować biblioteki, tylko powinna być lista zależności projektu w requirements.txt

Nie ma sprawy, tak czy tak to dla mnie mała różnica ważne abym w jakiś sposób uzyskać te "dodatkowe" funkcje i klasy, ponieważ obecnie repozytorium jest po prostu nie kompletne i nie można w pełni z tego repozytorium "zbudować" obecny program.

**Comment by efiku** [comment]
> Nie ma sprawy, tak czy tak to dla mnie mała różnica ważne abym w jakiś sposób uzyskać te "dodatkowe" funkcje i klasy, ponieważ obecnie repozytorium jest po prostu nie kompletne i nie można w pełni z tego repozytorium "zbudować" obecny program.

Jest przecież README.md w którym umieszczona jest instrukcja jak instalować zależności. 
Jednakże przypominam, że jest to obecnie początkowa wersja. 
Kolejną wersję @szmq wzbogaci o moduły i przepisze na bardziej obiektowy, a także doda plik requirements.txt ;)

**Comment by event15** [comment]
Chciałbym zauważyć, że jeśli issue jest zamykane to grzecznie jest napisać z jakiego powodu.

**Comment by efiku** [comment]
Wystarczy zerknąć, że zostały spełnione wszystkie zadania...
