### ISSUE TITLE
Funkcje matematyczne

### ISSUE THREAD

**Issue by event15** [CodersCommunity/Malyna#4]
Korzystając z bota, warto aby czasem pomógł nam rozwiązać proste zadania matematyczne. 

**Przykład:**

> [2+2]
> Odpowiedź: 4
> 
> [(2342 - 342)^2 + (23 - 234)^2]
> Odpowiedź: 4044521
> 
> [sqrt(121)]
> Odpowiedź: 11

Warto zaimplementować następujące operacje:
- dodawanie, odejmowanie, mnożenie, dzielenie, modulo
- sqrt, potęgowanie
- operacje bitowe: << >> & |
- operacje logiczne: and or not xor nand nor
- operacje porównania: != == <= >= 

**W jakim celu?**
Czasem się zdarza, że potrzeba na szybko coś obliczyć w trakcie tłumaczenia czegoś komuś. 
Czasem zdarza się, iż ktoś nie rozumie zasad działania operatorów bitowych, więc aby się nie pomylić wystarczy wykonać >[100101 & 110110] i bot poda wynik.

**Comment by efiku** [comment]
Dla pythona to nie problem:) Czytam wlasnie dokumentacje i portafi on
operowac na takich bajerach. Ale pasowaloby jakos to zabezpieczyc przed
potencjalnym crashem idt.

Ping @szmq i @adrian17
2 lut 2016 17:30 "Marek Woś" notifications@github.com napisał(a):

**Comment by event15** [comment]
Wiem, że to nie problem w pythonie - można nawet ciekawsze rzeczy wkleić, ale od czegoś można zacząć :)

**Comment by adrian17** [comment]
Znacznie prościej wykorzystać istniejące sandboxowane boty wykonujące kod Pythona. Zaraz przykładowo go zahostuję.
